import Svg, { Path } from "react-native-svg";

type IconProps = {
  size?: number;
  color?: string;
  filled?: boolean;
};

export function SearchIcon({
  size = 24,
  color = "#000",
  filled = false,
}: IconProps) {
  return (
    <Svg viewBox="0 0 24 24" width={size} height={size}>
      {filled ? (
        <Path
          fill={color}
          d="M10 2a8 8 0 015.293 13.707l5.5 5.5a1 1 0 01-1.414 1.414l-5.5-5.5A8 8 0 1110 2zm0 2a6 6 0 100 12 6 6 0 000-12z"
        />
      ) : (
        <Path
          fill={color}
          d="M23.707 22.293l-5.969-5.969a10.016 10.016 0 10-1.414 1.414l5.969 5.969a1 1 0 001.414-1.414zM10 18a8 8 0 118-8 8.009 8.009 0 01-8 8z"
        />
      )}
    </Svg>
  );
}

export function HomeIcon({
  size = 24,
  color = "#000",
  filled = false,
}: IconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 100 100">
      {filled ? (
        // Versión SÓLIDA - casa rellena con puerta como hueco
        <Path
          fill={color}
          fillRule="evenodd"
          d="M79.167 87.5H20.833c-4.596 0-8.333-3.739-8.333-8.333V51.725a8.28 8.28 0 012.441-5.892L47.054 13.72a4.165 4.165 0 015.892 0l32.113 32.113a8.275 8.275 0 012.441 5.892v27.441c0 4.595-3.739 8.334-8.333 8.334zM45.833 54.167c-4.596 0-8.333 3.739-8.333 8.333v25h25v-25c0-4.594-3.739-8.333-8.333-8.333h-8.334z"
        />
      ) : (
        // Versión OUTLINE - casa con contorno y hueco
        <Path
          fill={color}
          d="M79.167 87.5H58.333a4.165 4.165 0 01-4.167-4.167V62.5h-8.333v20.833a4.166 4.166 0 01-4.167 4.167H20.833c-4.596 0-8.333-3.739-8.333-8.333V51.725a8.28 8.28 0 012.441-5.892L47.054 13.72a4.165 4.165 0 015.892 0l32.113 32.113a8.275 8.275 0 012.441 5.892v27.441c0 4.595-3.739 8.334-8.333 8.334zM62.5 79.167h16.667V51.725L50 22.559 20.833 51.725v27.441H37.5V62.5c0-4.594 3.737-8.333 8.333-8.333h8.333c4.594 0 8.333 3.739 8.333 8.333v16.667z"
        />
      )}
    </Svg>
  );
}

export function FavoritesIcon({
  size = 24,
  color = "#000",
  filled = false,
}: IconProps) {
  return (
    <Svg viewBox="0 0 24 24" width={size} height={size}>
      {filled ? (
        // Versión SÓLIDA - estrella rellena
        <Path
          fill={color}
          d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
        />
      ) : (
        // Versión OUTLINE - estrella con contorno
        <Path
          fill={color}
          d="M23.836 8.794a3.179 3.179 0 00-3.067-2.226H16.4l-1.327-4.136a3.227 3.227 0 00-6.146 0L7.6 6.568H3.231a3.227 3.227 0 00-1.9 5.832L4.887 15l-1.352 4.187A3.178 3.178 0 004.719 22.8a3.177 3.177 0 003.8-.019L12 20.219l3.482 2.559a3.227 3.227 0 004.983-3.591L19.113 15l3.56-2.6a3.177 3.177 0 001.163-3.606zm-2.343 1.991l-4.144 3.029a1 1 0 00-.362 1.116l1.575 4.87a1.227 1.227 0 01-1.895 1.365l-4.075-3a1 1 0 00-1.184 0l-4.075 3a1.227 1.227 0 01-1.9-1.365l1.58-4.87a1 1 0 00-.362-1.116l-4.144-3.029a1.227 1.227 0 01.724-2.217h5.1a1 1 0 00.952-.694l1.55-4.831a1.227 1.227 0 012.336 0l1.55 4.831a1 1 0 00.952.694h5.1a1.227 1.227 0 01.724 2.217z"
        />
      )}
    </Svg>
  );
}
export const COLOMBIAN_MUNICIPALITIES = [
  "Abejorral",
  "Ábrego",
  "Abriaquí",
  "Acacías",
  "Acandí",
  "Acevedo",
  "Achí",
  "Agrado",
  "Agua de Dios",
  "Aguachica",
  "Aguada",
  "Aguadas",
  "Aguazul",
  "Agustín Codazzi",
  "Aipe",
  "Albán",
  "Albania",
  "Alcalá",
  "Aldana",
  "Alejandría",
  "Algarrobo",
  "Algeciras",
  "Almaguer",
  "Almeida",
  "Alpujarra",
  "Altamira",
  "Alto Baudó",
  "Altos del Rosario",
  "Alvarado",
  "Amagá",
  "Amalfi",
  "Ambalema",
  "Anapoima",
  "Ancuya",
  "Andalucía",
  "Andes",
  "Angelópolis",
  "Angostura",
  "Anolaima",
  "Anorí",
  "Anserma",
  "Ansermanuevo",
  "Anzá",
  "Anzoátegui",
  "Apartadó",
  "Apía",
  "Apulo",
  "Aquitania",
  "Aracataca",
  "Aranzazu",
  "Aratoca",
  "Arauca",
  "Arauquita",
  "Arbeláez",
  "Arboleda",
  "Arboledas",
  "Arboletes",
  "Arcabuco",
  "Arenal",
  "Argelia",
  "Ariguaní",
  "Arjona",
  "Armenia",
  "Armero",
  "Arroyohondo",
  "Astrea",
  "Ataco",
  "Ayapel",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Balboa",
  "Baranoa",
  "Baraya",
  "Barbacoas",
  "Barbosa",
  "Barichara",
  "Barranca de Upía",
  "Barrancabermeja",
  "Barrancas",
  "Barranco de Loba",
  "Barrancominas",
  "Barranquilla",
  "Becerril",
  "Belalcázar",
  "Belén",
  "Belén de los Andaquíes",
  "Belén de Umbría",
  "Bello",
  "Belmira",
  "Beltrán",
  "Berbeo",
  "Betania",
  "Betéitiva",
  "Betulia",
  "Bituima",
  "Boavita",
  "Bogotá",
  "Bochalema",
  "Bojacá",
  "Bojayá",
  "Bolívar",
  "Bosconia",
  "Boyacá",
  "Briceño",
  "Bucaramanga",
  "Bucarasica",
  "Buenaventura",
  "Buenavista",
  "Buenos Aires",
  "Buesaco",
  "Buga",
  "Bugalagrande",
  "Buriticá",
  "Busbanzá",
  "Cabrera",
  "Cabuyaro",
  "Cáceres",
  "Cachipay",
  "Cáchira",
  "Cácota",
  "Caicedo",
  "Caicedonia",
  "Caimito",
  "Cajamarca",
  "Cajibío",
  "Cajicá",
  "Calamar",
  "Calarcá",
  "Caldas",
  "Caldono",
  "Cali",
  "California",
  "Calima",
  "Caloto",
  "Campamento",
  "Campo de la Cruz",
  "Campoalegre",
  "Campohermoso",
  "Canalete",
  "Candelaria",
  "Cantagallo",
  "Cantón de San Pablo",
  "Cañasgordas",
  "Caparrapí",
  "Capitanejo",
  "Cáqueza",
  "Caracolí",
  "Caramanta",
  "Carcasí",
  "Carepa",
  "Carmen de Apicalá",
  "Carmen de Carupa",
  "Carolina del Príncipe",
  "Cartagena de Indias",
  "Cartagena del Chairá",
  "Cartago",
  "Carurú",
  "Casabianca",
  "Castilla la Nueva",
  "Caucasia",
  "Cepitá",
  "Cereté",
  "Cerinza",
  "Cerrito",
  "Cerro de San Antonio",
  "Cértegui",
  "Chachagüí",
  "Chaguaní",
  "Chalán",
  "Chámeza",
  "Chaparral",
  "Charalá",
  "Charta",
  "Chía",
  "Chibolo",
  "Chigorodó",
  "Chima",
  "Chimá",
  "Chimichagua",
  "Chinácota",
  "Chinavita",
  "Chinchiná",
  "Chinú",
  "Chipaque",
  "Chipatá",
  "Chiquinquirá",
  "Chíquiza",
  "Chiriguaná",
  "Chiscas",
  "Chita",
  "Chitagá",
  "Chitaraque",
  "Chivatá",
  "Chivor",
  "Choachí",
  "Chocontá",
  "Cicuco",
  "Ciénaga",
  "Ciénaga de Oro",
  "Ciénega",
  "Cimitarra",
  "Circasia",
  "Cisneros",
  "Ciudad Bolívar",
  "Clemencia",
  "Cocorná",
  "Coello",
  "Cogua",
  "Colombia",
  "Colón",
  "Colosó",
  "Cómbita",
  "Concepción",
  "Concordia",
  "Condoto",
  "Confines",
  "Consacá",
  "Contadero",
  "Contratación",
  "Convención",
  "Copacabana",
  "Coper",
  "Córdoba",
  "Corinto",
  "Coromoro",
  "Corozal",
  "Corrales",
  "Cota",
  "Cotorra",
  "Covarachía",
  "Coveñas",
  "Coyaima",
  "Cravo Norte",
  "Cuaspud",
  "Cubará",
  "Cubarral",
  "Cucaita",
  "Cucunubá",
  "Cúcuta",
  "Cucutilla",
  "Cuítiva",
  "Cumaral",
  "Cumaribo",
  "Cumbal",
  "Cumbitara",
  "Cunday",
  "Curillo",
  "Curití",
  "Curumaní",
  "Dabeiba",
  "Dagua",
  "Dibulla",
  "Distracción",
  "Dolores",
  "Donmatías",
  "Dosquebradas",
  "Duitama",
  "Duranía",
  "Ebéjico",
  "El Águila",
  "El Atrato",
  "El Bagre",
  "El Banco",
  "El Cairo",
  "El Calvario",
  "El Carmen",
  "El Carmen de Atrato",
  "El Carmen de Bolívar",
  "El Carmen de Chucurí",
  "El Carmen de Viboral",
  "El Carmen del Darién",
  "El Castillo",
  "El Cerrito",
  "El Charco",
  "El Cocuy",
  "El Colegio",
  "El Copey",
  "El Doncello",
  "El Dorado",
  "El Dovio",
  "El Espinal",
  "El Espino",
  "El Guacamayo",
  "El Guamo",
  "El Molino",
  "El Paso",
  "El Paujil",
  "El Peñol",
  "El Peñón",
  "El Piñón",
  "El Pital",
  "El Playón",
  "El Retén",
  "El Retorno",
  "El Roble",
  "El Rosal",
  "El Rosario",
  "El Santuario",
  "El Socorro",
  "El Tablón",
  "El Tambo",
  "El Tarra",
  "El Zulia",
  "Elías",
  "Encino",
  "Enciso",
  "Entrerríos",
  "Envigado",
  "Facatativá",
  "Falan",
  "Filadelfia",
  "Filandia",
  "Firavitoba",
  "Flandes",
  "Florencia",
  "Floresta",
  "Florián",
  "Florida",
  "Floridablanca",
  "Fómeque",
  "Fonseca",
  "Fortul",
  "Fosca",
  "Francisco Pizarro",
  "Fredonia",
  "Fresno",
  "Frontino",
  "Fuente de Oro",
  "Fundación",
  "Funes",
  "Funza",
  "Fúquene",
  "Fusagasugá",
  "Gachalá",
  "Gachancipá",
  "Gachantivá",
  "Gachetá",
  "Galán",
  "Galapa",
  "Galeras",
  "Gama",
  "Gamarra",
  "Gámbita",
  "Gámeza",
  "Garagoa",
  "Garzón",
  "Génova",
  "Gigante",
  "Ginebra",
  "Giraldo",
  "Girardot",
  "Girardota",
  "Girón",
  "Gómez Plata",
  "González",
  "Gramalote",
  "Granada",
  "Guaca",
  "Guacamayas",
  "Guacarí",
  "Guachené",
  "Guachetá",
  "Guachucal",
  "Guadalupe",
  "Guaduas",
  "Guaitarilla",
  "Gualmatán",
  "Guamal",
  "Guamo",
  "Guapí",
  "Guapotá",
  "Guaranda",
  "Guarne",
  "Guasca",
  "Guatapé",
  "Guataquí",
  "Guatavita",
  "Guateque",
  "Guática",
  "Guavatá",
  "Guayabal de Síquima",
  "Guayabetal",
  "Guayatá",
  "Güepsa",
  "Güicán",
  "Gutiérrez",
  "Hacarí",
  "Hatillo de Loba",
  "Hato Corozal",
  "Hato",
  "Hatonuevo",
  "Heliconia",
  "Herrán",
  "Herveo",
  "Hispania",
  "Hobo",
  "Honda",
  "Ibagué",
  "Icononzo",
  "Iles",
  "Imués",
  "Inírida",
  "Inzá",
  "Ipiales",
  "Íquira",
  "Isnos",
  "Itagüí",
  "Istmina",
  "Ituango",
  "Iza",
  "Jambaló",
  "Jamundí",
  "Jardín",
  "Jenesano",
  "Jericó",
  "Jerusalén",
  "Jesús María",
  "Jordán",
  "Juan de Acosta",
  "Junín",
  "Juradó",
  "La Apartada",
  "La Argentina",
  "La Belleza",
  "La Calera",
  "La Capilla",
  "La Ceja",
  "La Celia",
  "La Cruz",
  "La Cumbre",
  "La Dorada",
  "La Esperanza",
  "La Estrella",
  "La Florida",
  "La Gloria",
  "La Jagua de Ibirico",
  "La Jagua del Pilar",
  "La Llanada",
  "La Macarena",
  "La Merced",
  "La Mesa",
  "La Montañita",
  "La Palma",
  "La Paz",
  "La Peña",
  "La Pintada",
  "La Plata",
  "La Playa de Belén",
  "La Primavera",
  "La Salina",
  "La Sierra",
  "La Tebaida",
  "La Tola",
  "La Uvita",
  "La Unión",
  "La Uribe",
  "La Vega",
  "La Victoria",
  "La Virginia",
  "Labateca",
  "Labranzagrande",
  "Landázuri",
  "Lebrija",
  "Leiva",
  "Lejanías",
  "Lenguazaque",
  "Lérida",
  "Leticia",
  "Líbano",
  "Liborina",
  "Linares",
  "Litoral de San Juan",
  "Lloró",
  "López de Micay",
  "Lorica",
  "Los Andes",
  "Los Córdobas",
  "Los Palmitos",
  "Los Patios",
  "Los Santos",
  "Lourdes",
  "Luruaco",
  "Macanal",
  "Macaravita",
  "Maceo",
  "Machetá",
  "Madrid",
  "Magangué",
  "Magüí Payán",
  "Mahates",
  "Maicao",
  "Majagual",
  "Málaga",
  "Malambo",
  "Mallama",
  "Manatí",
  "Manaure Balcón del Cesar",
  "Manaure",
  "Maní",
  "Manizales",
  "Manta",
  "Manzanares",
  "Mapiripán",
  "Margarita",
  "María La Baja",
  "Marinilla",
  "Maripí",
  "Mariquita",
  "Marmato",
  "Marquetalia",
  "Marsella",
  "Marulanda",
  "Matanza",
  "Medellín",
  "Medio Atrato",
  "Medio Baudó",
  "Medio San Juan",
  "Medina",
  "Melgar",
  "Mercaderes",
  "Mesetas",
  "Milán",
  "Miraflores",
  "Miranda",
  "Mistrató",
  "Mitú",
  "Mocoa",
  "Mogotes",
  "Molagavita",
  "Momil",
  "Mongua",
  "Monguí",
  "Moniquirá",
  "Montebello",
  "Montecristo",
  "Montelíbano",
  "Montenegro",
  "Montería",
  "Monterrey",
  "Moñitos",
  "Morales",
  "Morelia",
  "Morroa",
  "Mosquera",
  "Motavita",
  "Murillo",
  "Murindó",
  "Mutatá",
  "Mutiscua",
  "Muzo",
  "Nariño",
  "Nátaga",
  "Natagaima",
  "Nechí",
  "Necoclí",
  "Neira",
  "Neiva",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nobsa",
  "Nocaima",
  "Norcasia",
  "Norosí",
  "Nóvita",
  "Nueva Granada",
  "Nuevo Belén de Bajirá",
  "Nuevo Colón",
  "Nunchía",
  "Nuquí",
  "Obando",
  "Ocamonte",
  "Ocaña",
  "Oiba",
  "Oicatá",
  "Olaya",
  "Olaya Herrera",
  "Onzaga",
  "Oporapa",
  "Orito",
  "Orocué",
  "Ortega",
  "Ospina",
  "Otanche",
  "Ovejas",
  "Pachavita",
  "Pacho",
  "Pácora",
  "Padilla",
  "Páez",
  "Paicol",
  "Pailitas",
  "Paime",
  "Paipa",
  "Pajarito",
  "Palermo",
  "Palestina",
  "Palmar de Varela",
  "Palmar",
  "Palmas del Socorro",
  "Palmira",
  "Palocabildo",
  "Pamplona",
  "Pamplonita",
  "Pandi",
  "Panqueba",
  "Páramo",
  "Paratebueno",
  "Pasca",
  "Pasto",
  "Patía",
  "Pauna",
  "Paya",
  "Paz de Ariporo",
  "Paz del Río",
  "Pedraza",
  "Pelaya",
  "Pensilvania",
  "Peque",
  "Pereira",
  "Pesca",
  "Piamonte",
  "Piedecuesta",
  "Piedras",
  "Piendamó",
  "Pijao",
  "Pijiño del Carmen",
  "Pinchote",
  "Pinillos",
  "Piojó",
  "Pisba",
  "Pitalito",
  "Pivijay",
  "Planadas",
  "Planeta Rica",
  "Plato",
  "Policarpa",
  "Polonuevo",
  "Ponedera",
  "Popayán",
  "Pore",
  "Potosí",
  "Pradera",
  "Prado",
  "Providencia",
  "Pueblo Viejo",
  "Pueblo Bello",
  "Pueblo Nuevo",
  "Pueblo Rico",
  "Pueblorrico",
  "Puente Nacional",
  "Puerres",
  "Puerto Asís",
  "Puerto Berrío",
  "Puerto Boyacá",
  "Puerto Caicedo",
  "Puerto Carreño",
  "Puerto Colombia",
  "Puerto Concordia",
  "Puerto Escondido",
  "Puerto Gaitán",
  "Puerto Guzmán",
  "Puerto Leguízamo",
  "Puerto Libertador",
  "Puerto Lleras",
  "Puerto López",
  "Puerto Nare",
  "Puerto Nariño",
  "Puerto Parra",
  "Puerto Rico",
  "Puerto Rondón",
  "Puerto Salgar",
  "Puerto Santander",
  "Puerto Tejada",
  "Puerto Triunfo",
  "Puerto Wilches",
  "Pulí",
  "Pupiales",
  "Puracé",
  "Purificación",
  "Purísima",
  "Quebradanegra",
  "Quetame",
  "Quibdó",
  "Quimbaya",
  "Quinchía",
  "Quípama",
  "Quipile",
  "Ragonvalia",
  "Ramiriquí",
  "Ráquira",
  "Recetor",
  "Regidor",
  "Remedios",
  "Remolino",
  "Repelón",
  "Restrepo",
  "Retiro",
  "Ricaurte",
  "Río de Oro",
  "Río Iró",
  "Río Quito",
  "Río Viejo",
  "Rioblanco",
  "Riofrío",
  "Riohacha",
  "Rionegro",
  "Riosucio",
  "Risaralda",
  "Rivera",
  "Roberto Payán",
  "Roldanillo",
  "Roncesvalles",
  "Rondón",
  "Rosas",
  "Rovira",
  "Sabana de Torres",
  "Sabanas de San Ángel",
  "Sabanagrande",
  "Sabanalarga",
  "Sabaneta",
  "Saboyá",
  "Sácama",
  "Sáchica",
  "Sahagún",
  "Saladoblanco",
  "Salamina",
  "Salazar de Las Palmas",
  "Saldaña",
  "Salento",
  "Salgar",
  "Samacá",
  "Samaná",
  "Samaniego",
  "Sampués",
  "Sandoná",
  "San Agustín",
  "San Alberto",
  "San Andrés",
  "San Andrés de Cuerquia",
  "San Andrés de Sotavento",
  "San Antero",
  "San Antonio",
  "San Antonio de Palmito",
  "San Antonio del Tequendama",
  "San Benito",
  "San Benito Abad",
  "San Bernardo",
  "San Bernardo del Viento",
  "San Calixto",
  "San Carlos",
  "San Carlos de Guaroa",
  "San Cayetano",
  "San Cristóbal",
  "San Diego",
  "San Eduardo",
  "San Estanislao",
  "San Fernando",
  "San Francisco",
  "San Gil",
  "San Jacinto del Cauca",
  "San Jacinto",
  "San Jerónimo",
  "San Joaquín",
  "San José",
  "San José de Albán",
  "San José de Miranda",
  "San José de Pare",
  "San José de Uré",
  "San José de la Montaña",
  "San José del Fragua",
  "San José del Guaviare",
  "San José del Palmar",
  "San Juan de Arama",
  "San Juan de Betulia",
  "San Juan de Rioseco",
  "San Juan de Urabá",
  "San Juan del Cesar",
  "San Juan Nepomuceno",
  "San Juanito",
  "San Lorenzo",
  "San Luis",
  "San Luis de Gaceno",
  "San Luis de Palenque",
  "San Marcos",
  "San Martín",
  "San Martín de Loba",
  "San Mateo",
  "San Miguel",
  "San Miguel de Sema",
  "San Onofre",
  "San Pablo",
  "San Pablo de Borbur",
  "San Pedro",
  "San Pedro de Cartago",
  "San Pedro de Urabá",
  "San Pedro de los Milagros",
  "San Pelayo",
  "San Rafael",
  "San Roque",
  "San Sebastián",
  "San Sebastián de Buenavista",
  "San Vicente",
  "San Vicente de Chucurí",
  "San Vicente del Caguán",
  "San Zenón",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Bárbara de Pinto",
  "Santa Catalina",
  "Santa Cruz de Mompós",
  "Santa Fe de Antioquia",
  "Santa Helena del Opón",
  "Santa Isabel",
  "Santa Lucía",
  "Santa María",
  "Santa Marta",
  "Santa Rosa",
  "Santa Rosa de Cabal",
  "Santa Rosa de Osos",
  "Santa Rosa de Viterbo",
  "Santa Rosa del Sur",
  "Santa Rosalía",
  "Santa Sofía",
  "Santacruz",
  "Santana",
  "Santander de Quilichao",
  "Santiago",
  "Santo Domingo",
  "Santo Domingo de Silos",
  "Santo Tomás",
  "Santuario",
  "Sapuyes",
  "Saravena",
  "Sardinata",
  "Sasaima",
  "Sativanorte",
  "Sativasur",
  "Segovia",
  "Sesquilé",
  "Sevilla",
  "Siachoque",
  "Sibaté",
  "Sibundoy",
  "Silvania",
  "Silvia",
  "Simacota",
  "Simijaca",
  "Simití",
  "Sincé",
  "Sincelejo",
  "Sipí",
  "Sitionuevo",
  "Soacha",
  "Soatá",
  "Socha",
  "Socotá",
  "Sogamoso",
  "Solano",
  "Soledad",
  "Solita",
  "Somondoco",
  "Sonsón",
  "Sopetrán",
  "Soplaviento",
  "Sopó",
  "Sora",
  "Soracá",
  "Sotaquirá",
  "Sotará",
  "Suaita",
  "Suán",
  "Suárez",
  "Suaza",
  "Subachoque",
  "Sucre",
  "Suesca",
  "Supatá",
  "Supía",
  "Suratá",
  "Susa",
  "Susacón",
  "Sutamarchán",
  "Sutatausa",
  "Sutatenza",
  "Tabio",
  "Tadó",
  "Talaigua Nuevo",
  "Tamalameque",
  "Támara",
  "Tame",
  "Támesis",
  "Taminango",
  "Tangua",
  "Tarazá",
  "Tarqui",
  "Tarso",
  "Tasco",
  "Taraira",
  "Tauramena",
  "Tausa",
  "Tello",
  "Tena",
  "Tenerife",
  "Tenjo",
  "Tenza",
  "Teorama",
  "Teruel",
  "Tesalia",
  "Tibacuy",
  "Tibaná",
  "Tibasosa",
  "Tibirita",
  "Tibú",
  "Tierralta",
  "Timaná",
  "Timbío",
  "Timbiquí",
  "Tinjacá",
  "Tipacoque",
  "Tiquisio",
  "Titiribí",
  "Toca",
  "Tocaima",
  "Tocancipá",
  "Togüí",
  "Toledo",
  "Tolú",
  "Tolú Viejo",
  "Tona",
  "Tópaga",
  "Topaipí",
  "Toribío",
  "Toro",
  "Tota",
  "Totoró",
  "Trinidad",
  "Trujillo",
  "Tubará",
  "Tuchín",
  "Tuluá",
  "Tumaco",
  "Tunja",
  "Tununguá",
  "Túquerres",
  "Turbaco",
  "Turbaná",
  "Turbo",
  "Turmequé",
  "Tuta",
  "Tutazá",
  "Ubalá",
  "Ubaque",
  "Ubaté",
  "Ulloa",
  "Úmbita",
  "Une",
  "Unión Panamericana",
  "Unguía",
  "Uramita",
  "Uribia",
  "Urrao",
  "Urumita",
  "Usiacurí",
  "Útica",
  "Valdivia",
  "Valencia",
  "Valle de San José",
  "Valle de San Juan",
  "Valle del Guamuez",
  "Valledupar",
  "Valparaíso",
  "Vegachí",
  "Vélez",
  "Venadillo",
  "Venecia",
  "Ventaquemada",
  "Vergara",
  "Versalles",
  "Vetas",
  "Vianí",
  "Victoria",
  "Vigía del Fuerte",
  "Vijes",
  "Villa Caro",
  "Villa de Leyva",
  "Villa del Rosario",
  "Villa Rica",
  "Villagarzón",
  "Villagómez",
  "Villahermosa",
  "Villamaría",
  "Villanueva",
  "Villapinzón",
  "Villarrica",
  "Villavicencio",
  "Villavieja",
  "Villeta",
  "Viotá",
  "Viracachá",
  "Vista Hermosa",
  "Viterbo",
  "Yacopí",
  "Yacuanquer",
  "Yaguará",
  "Yalí",
  "Yarumal",
  "Yolombó",
  "Yondó",
  "Yopal",
  "Yotoco",
  "Yumbo",
  "Zambrano",
  "Zapatoca",
  "Zapayán",
  "Zaragoza",
  "Zarzal",
  "Zetaquira",
  "Zipacón",
  "Zipaquirá",
  "Zona Bananera",
] as const;
